//
// Created by neven on 13-Aug-26.
//

#ifndef UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_MAIN_H
#define UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_MAIN_H


class Main
{
};


#endif //UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_MAIN_H
