//
// Created by d-sava on 23. 8. 2026..
//

#ifndef UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_OBLIK_H
#define UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_OBLIK_H

class Oblik {

};


#endif //UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_OBLIK_H
