//
// Created by neven on 22-Aug-26.
//

#ifndef UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_TACKA_H
#define UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_TACKA_H


class Tacka
{
};


#endif //UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_TACKA_H
