//
// Created by neven on 22-Aug-26.
//

#ifndef UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_VEZBE7_OSTATAK_H
#define UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_VEZBE7_OSTATAK_H


class vezbe7_ostatak
{
};


#endif //UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_VEZBE7_OSTATAK_H
