//
// Created by dimit on 4.7.2026..
//

#ifndef UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_MAIN_H
#define UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_MAIN_H

class main
{
};


#endif //UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_MAIN_H
