//
// Created by d-sava on 13. 7. 2026..
//

#ifndef UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_TEST_H
#define UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_TEST_H


class test {
};


#endif //UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_TEST_H
