//
// Created by neven on 05-Sep-26.
//

#ifndef UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_MAIN_H
#define UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_MAIN_H


class main
{
};


#endif //UNIVERSITY_CPP_IMPLEMENTED_ALGORITHMS_MAIN_H
